# Generated by Django 5.1b1 on 2025-04-24 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPageViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('url', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UniqueVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('ip_address', 'user_agent')},
            },
        ),
    ]
