# Generated by Django 5.0 on 2025-05-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquevisitor',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
