# Generated by Django 5.1b1 on 2025-05-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredMarkdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='An optional title for this Markdown content.', max_length=255, null=True)),
                ('markdown_content', models.TextField(help_text='The raw Markdown content.')),
                ('html_content', models.TextField(blank=True, editable=False, help_text='The HTML rendered from the Markdown content by django-spellbook.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stored Markdown Content',
                'verbose_name_plural': 'Stored Markdown Contents',
                'ordering': ['-updated_at'],
            },
        ),
    ]
