# Generated by Django 5.1b1 on 2025-08-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedmarkdown",
            name="html_content",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="HTML rendered from the Markdown by django-spellbook.",
            ),
        ),
    ]
