# api/serializers.py 

from rest_framework import serializers
from .models import StoredMarkdown

class StoredMarkdownSerializer(serializers.ModelSerializer):
    # html_content is now generated by the model's save() method,
    # so it will be up-to-date after save.
    # It's still good to mark it as read_only for API input.
    html_content = serializers.CharField(read_only=True)

    class Meta:
        model = StoredMarkdown
        fields = [
            'id',
            'title',
            'markdown_content',
            'html_content',
            'created_at',
            'updated_at'
        ]
        read_only_fields = ['id', 'html_content', 'created_at', 'updated_at']