# URL configuration for the API endpoints
from django.urls import (
    path,
)

from .views import (
    StoredMarkdownListCreateAPIView,
    StoredMarkdownDetailAPIView,
    RenderedMarkdownDetailAPIView,
    markdown_preview_api,
    random_markdown_api,
    spellblock_registry_api,
    style_preview_bg_core,
    style_preview_bg_status,
    style_preview_bg_specialty,
    style_preview_bg_system,
    style_preview_bg_base,
    style_preview_text_colors,
    style_preview_border_colors,
    style_preview_opacity_bg,
    style_preview_opacity_text,
    style_preview_opacity_border,
    style_preview_hover_bg,
    style_preview_hover_text,
    style_preview_hover_border,
    style_preview_spacing_p,
    style_preview_spacing_pxy,
    style_preview_spacing_psides,
    style_preview_spacing_m,
    style_preview_spacing_mb,
    style_preview_spacing_gap,
    style_preview_layout_flexbox_direction,
    style_preview_layout_flexbox_justify,
    style_preview_layout_grid,
    style_preview_layout_width,
    style_preview_layout_patterns_centered,
    style_preview_layout_patterns_sidebar,
    style_preview_layout_patterns_cards,
    style_preview_typography_sizes,
    style_preview_typography_weights,
    style_preview_typography_families,
    style_preview_typography_alignment,
    style_preview_typography_decoration,
    style_preview_typography_transform,
    style_preview_typography_patterns_title,
    style_preview_typography_patterns_body,
    style_preview_typography_patterns_label,
)

app_name = "api"

urlpatterns = [
    path(
        "stored-markdown/",
        StoredMarkdownListCreateAPIView.as_view(),
        name="storedmarkdown-list-create",
    ),
    path(
        "stored-markdown/<int:pk>/",
        StoredMarkdownDetailAPIView.as_view(),
        name="storedmarkdown-detail",
    ),
    path(
        "rendered-markdown/<int:pk>/",
        RenderedMarkdownDetailAPIView.as_view(),
        name="renderedmarkdown-detail",
    ),
    path(
        "markdown-preview/",
        markdown_preview_api,
        name="markdown-preview",
    ),
    path(
        "random-markdown/",
        random_markdown_api,
        name="random-markdown",
    ),
    path(
        "spellblock-registry/",
        spellblock_registry_api,
        name="spellblock-registry",
    ),
    # Style preview endpoints for HTMX color examples
    path(
        "styles/preview/bg-core/",
        style_preview_bg_core,
        name="style-preview-bg-core",
    ),
    path(
        "styles/preview/bg-status/",
        style_preview_bg_status,
        name="style-preview-bg-status",
    ),
    path(
        "styles/preview/bg-specialty/",
        style_preview_bg_specialty,
        name="style-preview-bg-specialty",
    ),
    path(
        "styles/preview/bg-system/",
        style_preview_bg_system,
        name="style-preview-bg-system",
    ),
    path(
        "styles/preview/bg-base/",
        style_preview_bg_base,
        name="style-preview-bg-base",
    ),
    path(
        "styles/preview/text-colors/",
        style_preview_text_colors,
        name="style-preview-text-colors",
    ),
    path(
        "styles/preview/border-colors/",
        style_preview_border_colors,
        name="style-preview-border-colors",
    ),
    path(
        "styles/preview/opacity-bg/",
        style_preview_opacity_bg,
        name="style-preview-opacity-bg",
    ),
    path(
        "styles/preview/opacity-text/",
        style_preview_opacity_text,
        name="style-preview-opacity-text",
    ),
    path(
        "styles/preview/opacity-border/",
        style_preview_opacity_border,
        name="style-preview-opacity-border",
    ),
    path(
        "styles/preview/hover-bg/",
        style_preview_hover_bg,
        name="style-preview-hover-bg",
    ),
    path(
        "styles/preview/hover-text/",
        style_preview_hover_text,
        name="style-preview-hover-text",
    ),
    path(
        "styles/preview/hover-border/",
        style_preview_hover_border,
        name="style-preview-hover-border",
    ),
    # Spacing preview endpoints for HTMX spacing examples
    path(
        "styles/preview/spacing-p/",
        style_preview_spacing_p,
        name="style-preview-spacing-p",
    ),
    path(
        "styles/preview/spacing-pxy/",
        style_preview_spacing_pxy,
        name="style-preview-spacing-pxy",
    ),
    path(
        "styles/preview/spacing-psides/",
        style_preview_spacing_psides,
        name="style-preview-spacing-psides",
    ),
    path(
        "styles/preview/spacing-m/",
        style_preview_spacing_m,
        name="style-preview-spacing-m",
    ),
    path(
        "styles/preview/spacing-mb/",
        style_preview_spacing_mb,
        name="style-preview-spacing-mb",
    ),
    path(
        "styles/preview/spacing-gap/",
        style_preview_spacing_gap,
        name="style-preview-spacing-gap",
    ),
    # Layout preview endpoints for HTMX layout examples
    path(
        "styles/preview/layout-flexbox-direction/",
        style_preview_layout_flexbox_direction,
        name="style-preview-layout-flexbox-direction",
    ),
    path(
        "styles/preview/layout-flexbox-justify/",
        style_preview_layout_flexbox_justify,
        name="style-preview-layout-flexbox-justify",
    ),
    path(
        "styles/preview/layout-grid/",
        style_preview_layout_grid,
        name="style-preview-layout-grid",
    ),
    path(
        "styles/preview/layout-width/",
        style_preview_layout_width,
        name="style-preview-layout-width",
    ),
    path(
        "styles/preview/layout-patterns-centered/",
        style_preview_layout_patterns_centered,
        name="style-preview-layout-patterns-centered",
    ),
    path(
        "styles/preview/layout-patterns-sidebar/",
        style_preview_layout_patterns_sidebar,
        name="style-preview-layout-patterns-sidebar",
    ),
    path(
        "styles/preview/layout-patterns-cards/",
        style_preview_layout_patterns_cards,
        name="style-preview-layout-patterns-cards",
    ),
    # Typography preview endpoints for HTMX typography examples
    path(
        "styles/preview/typography-sizes/",
        style_preview_typography_sizes,
        name="style-preview-typography-sizes",
    ),
    path(
        "styles/preview/typography-weights/",
        style_preview_typography_weights,
        name="style-preview-typography-weights",
    ),
    path(
        "styles/preview/typography-families/",
        style_preview_typography_families,
        name="style-preview-typography-families",
    ),
    path(
        "styles/preview/typography-alignment/",
        style_preview_typography_alignment,
        name="style-preview-typography-alignment",
    ),
    path(
        "styles/preview/typography-decoration/",
        style_preview_typography_decoration,
        name="style-preview-typography-decoration",
    ),
    path(
        "styles/preview/typography-transform/",
        style_preview_typography_transform,
        name="style-preview-typography-transform",
    ),
    path(
        "styles/preview/typography-patterns-title/",
        style_preview_typography_patterns_title,
        name="style-preview-typography-patterns-title",
    ),
    path(
        "styles/preview/typography-patterns-body/",
        style_preview_typography_patterns_body,
        name="style-preview-typography-patterns-body",
    ),
    path(
        "styles/preview/typography-patterns-label/",
        style_preview_typography_patterns_label,
        name="style-preview-typography-patterns-label",
    ),
]
